# https://github.com/Ezard/semantic-prs

enabled: true

titleAndCommits: true

allowMergeCommits: false

types:
  - feat
  - fix
  - docs
  - style
  - refactor
  - perf
  - test
  - build
  - ci
  - chore
  - revert
  - i18n
  - deps