files:
  - source: /mod/app/src/main/res/values/strings.xml
    translation: /mod/app/src/main/res/values-%android_code%/strings.xml
    content_segmentation: 0
    translatable_elements:
      - /resources/string
