apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}-actuator-basic-auth
data:
  user: {{ .Values.job.security.actuator.user.name | b64enc | quote }}
  password: {{ .Values.job.security.actuator.user.password | b64enc | quote }}
type: Opaque
