site_name: DataCap
site_url: https://databap.edurt.io/
site_author: EdurtIO
site_description: >-
  DataCap is integrated software for data transformation, integration and visualization.
repo_name: EdurtIO/datacap
repo_url: https://github.com/EdurtIO/datacap
edit_uri: "https://github.com/EdurtIO/datacap/blob/dev/docs/docs"

banners:
  - title: DataCap 1.11.0 is released
    link: /release-latest.html
    description: <a href="https://github.com/EdurtIO/datacap"> Do you ❤️ DataCap? Give us a 🌟 on GitHub </a>
  - title: Support apache cassandra
    link: /reference/connectors/cassandra.html
    description: newsletter 🎉

copyright: Copyright &copy; 2022 EdurtIO

theme:
  name: material
  custom_dir: overrides
  logo: assets/logo.png
  favicon: assets/logo.png
  include_search_page: true
  search_index_only: true
  language: en
  features:
    - content.code.annotate
    - content.tabs.link
#    - navigation.expand
    - navigation.indexes
    - navigation.path
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - content.tooltips
    - content.code.copy
#    - content.action.edit
#    - content.action.view
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/EdurtIO
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/qianmoQ/
  status:
    new: Recently added
    1.10.0: 1.10.0
    1.11.0: 1.11.0
  alternate:
    - name: English
      link: /en/
      lang: en
    - name: Chinese (Simplified)
      link: /zh/
      lang: zh
extra_css:
  - stylesheets/extra.css
  - css/datacap.css
extra_javascript:
  - js/datacap.js
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: EdurtIO
      repo: datacap
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

use_directory_urls: false
plugins:
  - i18n:
      default_language: en
      languages:
        en: English
        zh: Chinese (Simplified)
  - search
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true
      type: date
  - git-authors
  - redirects:
      redirect_maps:
        release-latest.md: release/latest.md

nav:
  - Home:
    - index.md
  - Documentation:
      - Installation:
        - Deploying in Self Host: reference/get_started/install.md
        - Deploying in Docker: reference/get_started/install_containers.md
        - Deploying in Rainbond: reference/get_started/install_rainbond.md
      - Query: reference/get_started/query.md
      - Clients:
        - Command line interface: reference/clients/cli.md
      - User Manager:
          - Basic:
            - DataSource: reference/admin/datasource/home.md
            - Snippet: reference/admin/snippet/home.md
          - Monitor:
            - Processor: reference/admin/processor/home.md
          - History:
            - Query History: reference/get_started/history.md
      - System Setting:
          - Basic:
            - Functions: reference/admin/functions/home.md
          - Template:
            - Sql: reference/admin/template/sql/home.md
      - Connecting to connectors:
        - reference/connectors/index.md
        - Apache Cassandra: reference/connectors/cassandra.md
        - JDBC:
          - Hologres: reference/connectors/jdbc/hologres.md
          - StarRocks: reference/connectors/jdbc/starrocks.md
          - Apache Doris: reference/connectors/jdbc/doris.md
          - DuckDB: reference/connectors/jdbc/duckdb.md
          - Yandex Database:  reference/connectors/jdbc/ydb.md
          - Snowflake: reference/connectors/jdbc/snowflake.md
          - MySQL: reference/connectors/jdbc/mysql.md
          - ClickHouse: reference/connectors/jdbc/clickhouse.md
        - Native:
          - Apache Pinot: reference/connectors/jdbc/pinot.md
          - Apache Hadoop:
            - HDFS: reference/connectors/native/hadoop/hdfs.md
          - H2 Database: reference/connectors/native/h2.md
          - Apache Kafka:
            - reference/connectors/native/kafka/index.md
            - SHOW TOPICS: reference/sql_syntax/connectors/native/kafka/show_topics.md
            - SHOW CONSUMERS: reference/sql_syntax/connectors/native/kafka/show_consumers.md
            - SHOW DATABASES: reference/sql_syntax/connectors/native/kafka/show_databases.md
            - SHOW TABLES: reference/sql_syntax/connectors/native/kafka/show_tables.md
          - Aliyun OSS: reference/connectors/native/alioss.md
          - Zookeeper: reference/connectors/native/zookeeper.md
          - Redis: reference/connectors/native/redis.md
        - Http:
          - QuestDB: reference/connectors/http/questdb.md
          - GreptimeDB: reference/connectors/http/greptimedb.md
          - CeresDB: reference/connectors/http/ceresdb.md
          - ClickHouse: reference/connectors/http/clickhouse.md
  - Developer guide:
      - Development environment: developer_guide/env.md
      - Add a Plugin:
        - Java Implementation: developer_guide/plugin-java.md
        - Kotlin Implementation: developer_guide/plugin-kotlin.md
  - Release Note:
      - 1.11.0 (latest): release/latest.md
      - 1.10.0: release/1.10.0.md
      - 1.9.0: release/1.9.0.md
      - 1.8.0: release/1.8.0.md
      - 1.7.0: release/1.7.0.md
      - 1.6.0: release/1.6.0.md
      - 1.5.0: release/1.5.0.md
      - 1.4.0: release/1.4.0.md
      - 1.3.0: release/1.3.0.md
      - 1.2.0: release/1.2.0.md
      - 1.1.0.20221115: release/1.1.0.20221115.md
      - 1.0.0.20221015: release/1.0.0.20221015.md
  - Resources:
    - Functions: resources/functions/home.md
  - Powered By: powered_by.md
