name: Java CI

on:
  push:
    branches: [ zingg ]






jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        profile: [ '-Pspark-3.1', '-Pspark-3.2', '-Pspark-3.3' ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: maven
      - name: Install secondstring and thirdparty
        run: mvn initialize
      - name: Build ${{ matrix.profile }} profile with Maven
        run: mvn --batch-mode ${{ matrix.profile }} clean compile package
