name: Build GUI

on:
  push:
    branches: [ slimevr-server ]















jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
          cache: 'npm'

      - name: Build
        run: |
          npm ci
          cd gui
          npm run lint

  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    env:
      # Don't mark warnings as errors
      CI: false

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - if: matrix.os == 'ubuntu-20.04'
        name: Set up Linux dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf
          # Increment to invalidate the cache
          version: 1.0
          # Enables a workaround to attempt to run pre and post install scripts
          execute_install_scripts: true
          # Disables uploading logs as a build artifact
          debug: false

      - name: Cache cargo dependencies
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: "${{ matrix.os }}"

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
          cache: 'npm'

      - name: Build
        run: |
          npm ci
          npm run skipbundler

      - if: matrix.os == 'windows-latest'
        name: Upload a Build Artifact (Windows)
        uses: actions/upload-artifact@v3
        with:
          # Artifact name
          name: SlimeVR-GUI-Windows
          # A file, directory or wildcard pattern that describes what to upload
          path: target/release/slimevr.exe

      - if: matrix.os == 'ubuntu-20.04'
        name: Upload a Build Artifact (Linux)
        uses: actions/upload-artifact@v3
        with:
          # Artifact name
          name: SlimeVR-GUI-Linux
          # A file, directory or wildcard pattern that describes what to upload
          path: target/release/slimevr

      - if: matrix.os == 'macos-latest'
        name: Upload a Build Artifact (macOS)
        uses: actions/upload-artifact@v3
        with:
          # Artifact name
          name: SlimeVR-GUI-macOS
          # A file, directory or wildcard pattern that describes what to upload
          path: target/release/slimevr
