# This is a basic workflow to help you get started with Actions

name: Build Windows

# Controls when the action will run.
on:
  push:
    branches: [ aliyundrive-webdav ]























jobs:
  buildx:
    runs-on: ${{ matrix.target.os }}
    strategy:
      matrix:
        target:
          - { os: windows-2022, arch: amd64, suffix: windows }
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Get current date
        id: date
        run: echo "::set-output name=today::$(date +'%Y%m%d')"
      -
        name: Setup Graalvm
        uses: graalvm/setup-graalvm@v1.0.12
        with:
          version: '22.3.2'
          java-version: '17'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cache: 'gradle'
      # Set VERSION_INFORMATION
      - run: echo "VERSION_INFORMATION=$(./gradlew --no-daemon -q ciPrintVersionInformation)" >> $env:GITHUB_ENV
      -
        name: Build project
        run: ./gradlew --no-daemon nativeCompile
      -
        run: mv build/native/nativeCompile/aliyundrive-webdav.exe build/native/nativeCompile/aliyundrive-webdav-${{matrix.target.suffix}}-${{matrix.target.arch}}.exe
      -
        name: Archive artifacts
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: 'aliyundrive-webdav-${{matrix.target.suffix}}-${{matrix.target.arch}}.exe.zip'
          directory: 'build/native/nativeCompile/'
          path: "./aliyundrive-webdav-${{matrix.target.suffix}}-${{matrix.target.arch}}.exe"
      -
        name: Upload artifacts
        uses: Wandalen/wretry.action@v1.0.36
        with:
          action: bxb100/action-upload-webdav@v1
          with: |
            webdav_address: ${{secrets.WEBDAV_ADDRESS}}
            webdav_username: ${{secrets.WEBDAV_USERNAME}}
            webdav_password: ${{secrets.WEBDAV_PASSWORD}}
            webdav_upload_path: "/${{ env.VERSION_INFORMATION }}"
            files: |
              build/native/nativeCompile/aliyundrive-webdav-${{matrix.target.suffix}}-${{matrix.target.arch}}.exe.zip
          attempt_limit: 3
          attempt_delay: 0
