name: 'Delete old workflow runs'
on:
  push:
    branches: [ sketchware-pro ]












jobs:
  deleteWorkflowRuns:
    name: Delete old workflow run(s)
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2.0.3
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: ${{ github.event.inputs.days }}
          keep_minimum_runs: ${{ github.event.inputs.minimum_runs }}
