name: Deploy CI Workflow
on:
  push:
    branches: [ openhufu ]




jobs:
  build:
    name: Deploy
    if: github.repository_owner == 'BUAA-BDA'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: ./scripts/build/package.sh
    - name: Deploy to GitHub Packages
      run: ./scripts/build/deploy.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload Hu-Fu Release Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: OpenHuFu-release
        path: release
