# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Frontend CI

on:
  push:
    branches: [ bk-job ]









jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: echo "npm version=$(npm -v)"
      - name: build
        run: |
          export JOB_VERSION=3.latest
          npm i --legacy-peer-deps && npm run build
        working-directory: src/frontend
