name: Publish Native Android Libraries

on:
  push:
    branches: [ capacitor-plugins ]





































jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.CAP_GH_RELEASE_TOKEN }}
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
    - name: Grant execute permission for publishing script
      run: chmod +x ./scripts/publish-android.sh
    - name: Run publish script
      working-directory: ./scripts
      env:
        GITHUB_PLUGINS: ${{ github.event.inputs.plugins }}
        GITHUB_CAPACITOR_VERSION: ${{ github.event.inputs.capacitor-version }}
        ANDROID_OSSRH_USERNAME: ${{ secrets.ANDROID_OSSRH_USERNAME }}
        ANDROID_OSSRH_PASSWORD: ${{ secrets.ANDROID_OSSRH_PASSWORD }}
        ANDROID_SIGNING_KEY_ID: ${{ secrets.ANDROID_SIGNING_KEY_ID }}
        ANDROID_SIGNING_PASSWORD: ${{ secrets.ANDROID_SIGNING_PASSWORD }}
        ANDROID_SIGNING_KEY: ${{ secrets.ANDROID_SIGNING_KEY }}
        ANDROID_SONATYPE_STAGING_PROFILE_ID: ${{ secrets.ANDROID_SONATYPE_STAGING_PROFILE_ID }}
      run: ./publish-android.sh
