name: Validation

on:
  push:
    branches: [ hilla ]














jobs:
  test-all:
    name: Tests Summary
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - run: 'echo "No build required"'
