name: X-BachInfo

on:
  push:
    branches: [ jreleaser ]

















jobs:
  update-bach-info:
    name: Update bach-info
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: jreleaser/bach-info
          ref: main
          fetch-depth: 0
          token: ${{ secrets.gh-access-token }}

      - name: Download script
        shell: bash
        run: |
          curl -sL https://raw.githubusercontent.com/jreleaser/jreleaser/main/.github/scripts/update-bach-info.sh --output update-bach-info.sh
          chmod +x update-bach-info.sh

      - name: Commit
        shell: bash
        env:
          TAG: ${{ inputs.project-tag }}
          VERSION: ${{ inputs.project-version }}
          GH_BOT_EMAIL: ${{ vars.GH_BOT_EMAIL }}
        run: sh update-bach-info.sh
