name: Test

on:
  push:
    branches: [ tai-e ]




jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Run Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            test --tests pascal.taie.TaieTestSuite
            --scan

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        if: env.CODECOV_TOKEN != null
