# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Trino CI with Maven

on:
  push:
    branches: [ arctic ]






























jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Install dependency with Maven
        run: mvn clean install -DskipTests -pl 'ams/api,core,hive' -am -B

      - name: Build with Maven
        run: mvn clean test -pl 'trino' -B -ntp

      - name: Code coverage
        uses: codecov/codecov-action@v3
        with:
          verbose: true
          flags: trino
